environment:
  matrix:
    - nodejs_version: 6
      test_suite: "simple"
    - nodejs_version: 6
      test_suite: "installs"
    - nodejs_version: 6
      test_suite: "kitchensink"
    - nodejs_version: 4
      test_suite: "simple"
    - nodejs_version: 4
      test_suite: "installs"
    - nodejs_version: 4
      test_suite: "kitchensink"

cache:
  - node_modules
  - packages\react-scripts\node_modules

clone_depth: 50

matrix:
  fast_finish: true

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build: off

test_script:
  - node --version
  - npm --version
  - ps: $env:SKIP = bash -c ./tasks/should-skip.sh
  - ps: if ($env:SKIP -ne 0) { bash -c ./tasks/e2e-$env:test_suite.sh }
